version: '3'

services:
  app:
    image: pedrocamargo3008/api-blog-test:dev
    entrypoint: .docker/entrypoint.sh
    container_name: blog-api-app
    ports:
      - "3002:3002"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: pedrocamargo3008/api-postgres-test:dev
    container_name: blog-api-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=blog
